### ISSUE TITLE
Demo instance?

### ISSUE THREAD

**Issue by apowers313** [Mastercard/fido2-rp-spring#1]
If you have a server running some place public (Digital Ocean, AWS, etc.) I could probably use the collection of authenticators that I have to make sure it works with them. If it's not running publicly, maybe I can set it up on webauthn.org so that people can play with it.

Let me know what you think.

**Comment by dawid-nowak** [comment]
sorry for a late reply, i completely missed your comment. we are working on publishing it at the moment. but if you want to run in behind webauthn.org that would be great.
